.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. testcoin_qt test_testcoin_qt
clean: FORCE
	$(MAKE) -C .. testcoin_qt_clean test_testcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_testcoin_qt_check
testcoin-qt testcoin-qt.exe: FORCE
	 $(MAKE) -C .. testcoin_qt
