#!/bin/bash

# This is a thin wrapper around testcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using testcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_TESTCOIND

# Grab the value of $REAL_TESTCOINCLI which may be testcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_TESTCOINCLI}" "$@" | sed 's/\r//'
